defmodule Angio.Repo.Migrations.CreateTableSatsPressures do
  use Ecto.Migration

  def change do
    create table(:sats_pressures) do
      add(:aortic_pres_mean, :string)
      add(:pa_right_pres_mean, :string)
      add(:pa_pres_sys, :string)
      add(:rv_pres_dias, :string)
      add(:svc_pres_dias, :string)
      add(:ivc_pres_mean, :string)
      add(:svc_pres_mean, :string)
      add(:sao2_rv, :string)
      add(:sao2_ra_mid, :string)
      add(:ra_pres_x, :string)
      add(:rv_pres_sys, :string)
      add(:pa_left_pres_sys, :string)
      add(:sao2_hepatic_veins, :string)
      add(:sao2_rv_apex, :string)
      add(:sat_pres_meds, :string)
      add(:pcw_pres_dias, :string)
      add(:sao2_svc_low, :string)
      add(:sao2_pa, :string)
      add(:sat_pres_o2_inhalation, :string)
      add(:lv_pres_sys, :string)
      add(:ra_pres_v, :string)
      add(:pcw_pres_x, :string)
      add(:pa_right_pres_sys, :string)
      add(:pa_right_pres_dias, :string)
      add(:ventr_dias_fill_period, :string)
      add(:pcw_pres_h, :string)
      add(:pcw_pres_a, :string)
      add(:sao2_pa_left, :string)
      add(:pcw_pres_z, :string)
      add(:ra_pres_mean, :string)
      add(:pa_pres_mean, :string)
      add(:sao2_rv_mid, :string)
      add(:pa_left_pres_mean, :string)
      add(:sao2_lv, :string)
      add(:pcw_pres_v, :string)
      add(:aortic_pres_dias, :string)
      add(:svc_pres_sys, :string)
      add(:ventr_sys_ejc_period, :string)
      add(:sao2_ivc, :string)
      add(:sat_pres_hb, :string)
      add(:ivc_pres_sys, :string)
      add(:pcw_pres_c, :string)
      add(:aortic_pres_sys, :string)
      add(:uni_bsa, :string)
      add(:pcw_pres_mean, :string)
      add(:ra_pres_h, :string)
      add(:pa_pres_sys_na, :string)
      add(:ra_pres_dias, :string)
      add(:sao2_rv_outflow, :string)
      add(:ra_pres_a, :string)
      add(:pa_left_pres_dias, :string)
      add(:ra_pres_z, :string)
      add(:uni_qp_qs, :string)
      add(:pa_pres_mean_na, :string)
      add(:sat_pres_oxygen_consumption, :string)
      add(:lv_pres_mean, :string)
      add(:sao2_ao_distal, :string)
      add(:sao2_pcw, :string)
      add(:ivc_pres_dias, :string)
      add(:lv_pres_end_dias, :string)
      add(:pa_pres_dias, :string)
      add(:sao2_ra_low, :string)
      add(:sat_pres_notes, :string)
      add(:ra_pres_c, :string)
      add(:ra_pres_sys, :string)
      add(:sao2_ra_high, :string)
      add(:sao2_svc_high, :string)
      add(:rv_pres_mean, :string)
      add(:sao2_pa_right, :string)
      add(:sao2_ao_root, :string)
      add(:pcw_pres_y, :string)
      add(:pcw_pres_sys, :string)
      ### added fields######
      add(:sat_pulm_veins, :string)
      add(:sat_pres_start_dt, :date)
      add(:sat_pres_start_tm, :time)
      add(:sat_pres_end_dt, :date)
      add(:sat_pres_end_tm, :time)
      add(:ra_pres_y, :string)
      add(:sat_pres_heart_rate, :string)
      add(:hepatic_veins_pres, :string)

      add(:patient_id, :integer)
      add(:info_coronary_id, references(:info_coronaries, on_delete: :delete_all))
    end
  end
end
