defmodule Angio.Repo.Migrations.CreateEchoVentricleLefts do
  use Ecto.Migration

  def change do
    create table(:echo_ventricle_lefts) do
      add(:elv_lv_appearance_desc, :string)
      add(:elv_lv_appearance_other_text, :text)
      add(:elv_concentric_hyper_yn, :boolean, default: false, null: false)
      add(:elv_myocardial_mass_qualitative, :string)
      add(:elv_myocardial_mass_val, :string)
      add(:elv_myocardial_mass_method, :string)
      add(:elv_lv_shape_normal_yn, :boolean, default: false, null: false)
      add(:elv_lv_geometry_desc, :string)
      add(:elv_lved_cavity_size_desc, :string)
      add(:elv_lved_volume_val, :string)
      add(:elv_lved_volume_index, :string)
      add(:elv_lved_volume_method, :string)
      add(:elv_lves_volume_val, :string)
      add(:elv_lves_volume_method, :string)
      add(:elv_thrombus_tumour_yn, :boolean, default: false, null: false)
      add(:elv_thrombus_tumour_loc, :string)
      add(:elv_aneurism_shape_desc, :string)
      add(:elv_aneurism_pseudo_shape_desc, :string)
      add(:elv_wall_thick_normal_yn, :boolean, default: false, null: false)
      add(:elv_wall_thick_region, :string)
      add(:elv_wall_thick_region_qualitative, :string)
      add(:elv_wall_thick_region_name, :string)
      add(:elv_wall_thick_asym_hyper_desc, :string)
      add(:elv_lvpw_thick_sys_val, :string)
      add(:elv_lvpw_thick_diast_val, :string)
      add(:elv_lved_septal_thick_val, :string)
      add(:elv_lves_septal_thick_val, :string)
      add(:elv_lved_inferior_lateral_septal_thick_val, :string)
      add(:elv_lved_overall_septal_thick_desc, :string)
      add(:elv_lvid_lved_val, :string)
      add(:elv_lvid_lved_na, :boolean, default: false, null: false)
      add(:elv_lvid_lves_val, :string)
      add(:elv_lvid_lves_na, :boolean, default: false, null: false)
      add(:elv_lvot_desc, :string)
      add(:elv_lves_volume_index, :string)
      add(:elv_non_compaction_yn, :boolean, default: false, null: false)
      add(:elv_segment_17model, :string)
      add(:elv_ste_circ_peak_strain, :string)
      add(:elv_ste_radial_peak_strain, :string)
      add(:elv_notes, :text)
      add(:cardiac_echo_id, references(:cardiac_echoes, on_delete: :delete_all))
      timestamps()
    end
  end
end
