defmodule Angio.Repo.Migrations.CreateTreadmillExercises do
  use Ecto.Migration

  def change do
    create table(:treadmill_exercises) do
      add(:ext_dt, :date)
      add(:ext_tm, :time)
      add(:ext_lab_num, :string)
      add(:ext_lab_yr, :string)
      add(:ext_lab_id, :string)
      add(:ext_consent_yn, :boolean, default: false, null: false)
      add(:ext_doctor_lname, :string)
      add(:ext_doctor_fname, :string)
      add(:ext_technician_lname, :string)
      add(:ext_technician_fname, :string)
      add(:ext_referral_person, :string)
      add(:ext_is_done_yn, :boolean, default: false, null: false)
      add(:ext_not_done_reason, :string)
      add(:ext_indication, :string)
      add(:ext_limitations_relative, :string)
      add(:ext_limitations, :string)
      add(:ext_indication_notes, :text)
      add(:ext_protocole_used, :string)
      add(:ext_main_problem_cardiac_yn, :boolean, default: false, null: false)
      add(:ext_cad_pretest_probability, :string)
      add(:ext_mortality_cad_risk, :string)
      add(:ext_main_problem_pulm_yn, :boolean, default: false, null: false)
      add(:ext_main_problem_medical_yn, :boolean, default: false, null: false)
      add(:ext_main_problem_notes, :text)
      add(:ext_medications_yn, :boolean, default: false, null: false)
      add(:ext_anginal_meds_yn, :boolean, default: false, null: false)
      add(:ext_on_digoxin_yn, :boolean, default: false, null: false)
      add(:ext_on_bblockers_yn, :boolean, default: false, null: false)
      add(:ext_ecg_normal_pre_yn, :boolean, default: false, null: false)
      add(:ext_qrs_morphology_pre, {:array, :string})
      add(:ext_qwaves_pre, :string)
      add(:ext_st_depres_pre_yn, :boolean, default: false, null: false)
      add(:ext_st_depres_pre_val, :string)
      add(:ext_t_wave_inversion_pre_yn, :boolean, default: false, null: false)
      add(:ext_lv_hypertrophy_pre_yn, :boolean, default: false, null: false)
      add(:ext_pvc_pre_yn, :boolean, default: false, null: false)
      add(:ext_afib_pre_yn, :boolean, default: false, null: false)
      add(:ext_stages_completed, :string)
      add(:ext_stop_reason, :string)
      add(:ext_stop_reason_angina_yn, :boolean, default: false, null: false)
      add(:ext_stop_reason_other_yn, :boolean, default: false, null: false)
      add(:ext_need_hold_handrails_yn, :boolean, default: false, null: false)
      add(:ext_stopping_reason_notes, :text)
      add(:ext_bp_diast_rest, :string)
      add(:ext_bp_sys_rest, :string)
      add(:ext_bp_sys_max, :string)
      add(:ext_bp_diast_max, :string)
      add(:ext_heart_rate_rest, :string)
      add(:ext_heart_rate_achieved, :string)
      add(:ext_heart_rate_max_predicted, :string)
      add(:ext_st_elevation_max, :string)
      add(:ext_st_depres_max, :string)
      add(:ext_st_depres_max_duration, :string)
      add(:ext_st_depres_max_location, :string)
      add(:ext_st_slop_max, :string)
      add(:ext_mets, :string)
      add(:ext_watts, :string)
      add(:ext_duke_score, :string)
      add(:ext_borg_scale, :string)
      add(:ext_athens_score, :string)
      add(:ext_bp_sys_recovery, :string)
      add(:ext_bp_diast_recovery, :string)
      add(:ext_st_depres_recovery_val, :string)
      add(:ext_st_depres_recovery_location, :string)
      add(:ext_heart_rate_at_max_st_depres, :string)
      add(:ext_complication_yn, :boolean, default: false, null: false)
      add(:ext_cpr_post_yn, :boolean, default: false, null: false)
      add(:ext_bradycardia_post_yn, :boolean, default: false, null: false)
      add(:ext_cardio_shock_post_yn, :boolean, default: false, null: false)
      add(:ext_mi_post_yn, :boolean, default: false, null: false)
      add(:ext_angina_severe_post_yn, :boolean, default: false, null: false)
      add(:ext_compl_other_yn, :boolean, default: false, null: false)
      add(:ext_vt_post_yn, :boolean, default: false, null: false)
      add(:ext_compl_afib_post_yn, :boolean, default: false, null: false)
      add(:ext_compl_notes, :text)
      add(:ext_result, :string)
      add(:ext_result_notes, :text)
      add(:ext_recommendations, :text)
      add(:ext_cpx_age_vo2, :string)
      add(:ext_cpx_vo2_ventilatory_response, :string)
      add(:ext_cpx_ve_vco2_slope, :string)
      add(:ext_cpx_peak_mets, :string)
      add(:ext_cpx_peak_vo2, :string)
      add(:ext_va_treadmill_score, :string)
      add(:ext_aerobic_capacity_max, :string)
      add(:ext_notes, :text)
      add(:patient_id, references(:patients, on_delete: :delete_all))
      timestamps()
    end
  end
end
