defmodule Angio.Repo.Migrations.CreatePciFups do
  use Ecto.Migration

  def change do
    create table(:pci_fups) do
      add(:pfup_assessment_dt, :date)
      add(:pfup_reason, :string)
      add(:pfup_type, :string)
      add(:pfup_primary_fup_method, :string)
      add(:pfup_survival_status, :string)
      add(:pfup_clinical_improvement_yn, :boolean, default: false, null: false)
      add(:pfup_complications_after_pci, :boolean, default: false, null: false)
      add(:pfup_death_dt, :date)
      add(:pfup_death_cause, :string)
      add(:pfup_prior_stent_type, :string)
      add(:pfup_stent_thrombosis_yn, :boolean, default: false, null: false)
      add(:pfup_stent_thrombosis_dt, :date)
      add(:pfup_stent_thrombosis_timing, :string)
      add(:pfup_readmission_yn, :boolean, default: false, null: false)
      add(:pfup_readmission_dt, :date)
      add(:pfup_readmission_reason, :string)
      add(:pfup_stroke_yn, :boolean, default: false, null: false)
      add(:pfup_stroke_dt, :date)
      add(:pfup_angio_after_yn, :boolean, default: false, null: false)
      add(:pfup_angio_after_dt, :date)
      add(:pfup_angio_after_results, :text)
      add(:pfup_pci_after_yn, :boolean, default: false, null: false)
      add(:pfup_pci_after_dt, :date)
      add(:pfup_pci_location, {:array, :string})
      add(:pfup_cabg_after_yn, :boolean, default: false, null: false)
      add(:pfup_cabg_after_dt, :date)
      add(:pfup_cabage_notes, :text)
      add(:pfup_other_intevention_yn, :boolean, default: false, null: false)
      add(:pfup_other_intevention_notes, :string)
      add(:pfup_infarction_yn, :boolean, default: false, null: false)
      add(:pfup_new_infarction_dt, :date)
      add(:pfup_old_infarction_location, :string)
      add(:pfup_new_infarction_location, :string)
      add(:pfup_new_infarction_treatment, :string)
      add(:pfup_infarction_notes, :text)
      add(:pfup_chest_pain, :string)
      add(:pfup_angina_type, :string)
      add(:pfup_angina_total_num, :string)
      add(:pfup_angina_duration, :string)
      add(:pfup_angina_last_episode_dt, :date)
      add(:pfup_nyha, :string)
      add(:pfup_angina_class_canadian, :string)
      add(:pfup_aspirin_yn, :boolean, default: false, null: false)
      add(:pfup_beta_blocker_yn, :boolean, default: false, null: false)
      add(:pfup_nitrates_yn, :boolean, default: false, null: false)
      add(:pfup_diuretics_yn, :boolean, default: false, null: false)
      add(:pfup_statin_yn, :boolean, default: false, null: false)
      add(:pfup_no_statin_yn, :boolean, default: false, null: false)
      add(:pfup_antiplatelet_yn, :boolean, default: false, null: false)
      add(:pfup_thienopyridines, :string)
      add(:pfup_arb_yn, :boolean, default: false, null: false)
      add(:pfup_anticoagulant_yn, :boolean, default: false, null: false)
      add(:pfup_thienopyridines_types, :string)
      add(:pfup_xa_inhibitors, :string)
      add(:pfup_ace_yn, :boolean, default: false, null: false)
      add(:pfup_rehabilitation, :string)
      add(:pfup_notes, :text)
      add(:patient_id, references(:patients, on_delete: :delete_all))
      timestamps()
    end
  end
end
